### ISSUE TITLE
How can I reproduce THUMOS14-Features?

### ISSUE THREAD

**Issue by Keiku** [ispc-lab/ACM-Net#2]
Is there a tutorial that starts with the original THUMOS14 instead of starting with the THUMOS14-Features given?

**Comment by sanqingqu** [comment]
First of all, thank you for your interest in our ACM-Net.  In fact, we recommend you to utilize our provided pre-trained features of the THUMOS-14 and the ActivityNet-1.3 dataset for your research since the feature extraction is very tedious and boring. 
For the pre-trained feature extraction, we refer you to the official [TensorFlow-based I3D repo](https://github.com/deepmind/kinetics-i3d) and the third-party [PyTorch-based I3D repo](https://github.com/piergiaj/pytorch-i3d). There are detailed operations guides for the feature extraction.

**Comment by Keiku** [comment]
Thank you for detailed explanation. I will check the link.
